import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { toastSuccessMessage } from "../utils/toastMessage/toastMessage"
import { useEffect } from 'react';
import CreateProduct from './createProduct';
import { ApiRegister } from '../apis/services/apiRegister/ApiRegister';
import MyLayout from "../component/layout/Layout";
import Link from "next/link"


export default function Home() {

  useEffect(() => {

      console.log('[Node.js only] ENV_VARIABLE:', process.env.ENV_VARIABLE)
  console.log(
    '[Node.js only] ENV_LOCAL_VARIABLE:',
    process.env.ENV_LOCAL_VARIABLE
  )

    const _handleRequestApi = async () => {
      let loadData = null;
      let dataUrl = '/app/api/v1/factor/shop/Khatun/uncompleted/';
      let response = await ApiRegister().apiRequest(loadData, 'get', dataUrl, false);
      console.log("res uncom :", response);
      // setImages(response);//==> output: {}
  }
  _handleRequestApi();

    // toastSuccessMessage('success');



  }, []);

  return (
    

    <div className="container">
      <div className="m-5 p-4 rounded bg-white">
        <CreateProduct />
      </div>

    </div>


    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>



    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/master/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>

  )
}


Home.Layout = MyLayout;
